### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by hrqmonteiro** [shaunsingh/oxocarbon.nvim#8]
![image](https://user-images.githubusercontent.com/17055027/184260981-982cc55c-40b0-4a29-881f-91ad2f3f77f4.png)

**Comment by namzug16** [comment]
Hey @hrqmonteiro did you find a solution ?

**Comment by Rawnly** [comment]
same here

**Comment by shaunsingh** [comment]
should be fixed now

**Comment by namzug16** [comment]
<img width="1440" alt="Screenshot 2022-09-07 at 17 15 12" src="https://user-images.githubusercontent.com/77210010/188914964-baba7e84-5b85-4f22-b19d-09272461f539.png">

I am still getting the error @shaunsingh , I'm trying to install it on astrovim

**Comment by sirutBuasai** [comment]
Just tried updating and its still persists.

**Comment by sirutBuasai** [comment]
doing a `rustup update` removes the error in this issue for me but now when doing `colorscheme oxocarbon` I get booted out of neovim with this error instead.

<img width="1787" alt="Screen Shot 2022-09-07 at 11 31 25" src="https://user-images.githubusercontent.com/73297481/188918936-e235a739-72a1-475b-aa0e-52dd8d80a298.png">

**Comment by Rawnly** [comment]
> doing a `rustup update` removes the error in this issue for me but now when doing `colorscheme oxocarbon` I get booted out of neovim with this error instead.

same (trying to install on astrovim via packer)

**Comment by Rawnly** [comment]
@shaunsingh  Seems to be an `nvim-oxi` problem. It panics on a result `unwrap` (`lua.rs:45:12`)

**Comment by Rawnly** [comment]
I've been able to fix this by installing the stable version of  `nvim-oxi` (which is the `0.1.2`) and rolling back the changes of the PR #13 

You can look at the code on this repo [rawnly/oxocarbon.nvim](https://github.com/rawnly/oxocarbon.nvim). 

I'll open a PR
